setwd("/Users/apple/Desktop")
file <- read.csv("household_power_consumption.txt", header = T, sep = ';', stringsAsFactors = F, nrows = 2075259)
data <- subset (file, Date %in% c("1/2/2007", "2/2/2007"))
data$Date <- strptime(data$Date, format = "%d/%m/%Y")
hist(as.numeric(data$Global_active_power), main = "Global Active Power", xlab = "Global Active Power (kilowatts)", ylab = "Frequency", col = "Red")
png("plot1.png", width = 480, height = 480)
dev.off()
